from . import product_template
from . import product_product
from . import sale_order_template
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import sale_serial_plan
from . import container_bulk_update
from . import dispatch
from . import sale_serial_wizard
from . import stock_move
from . import stock_move_line
from . import stock_move_line_view
from . import stock_lot
from . import stock_picking
